# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # documentation
  - package-ecosystem: 'pip'
    directory: '/documentation'
    schedule:
      interval: 'monthly'
    groups:
      documentation:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/documentation'
    schedule:
      interval: 'monthly'
    groups:
      documentation:
        patterns:
          - '*'

  # segmenter
  - package-ecosystem: 'pip'
    directory: '/segmenter'
    schedule:
      interval: 'monthly'
    groups:
      segmenter:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/segmenter'
    schedule:
      interval: 'monthly'
    groups:
      segmenter:
        patterns:
          - '*'

  # controller
  - package-ecosystem: 'pip'
    directory: '/controller'
    schedule:
      interval: 'monthly'
    groups:
      controller:
        patterns:
          - '*'

  # github actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      github-actions:
        patterns:
          - '*'

  # node-red
  - package-ecosystem: 'npm'
    directory: '/node-red'
    schedule:
      interval: 'monthly'
    groups:
      node-red:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/node-red/nodes'
    schedule:
      interval: 'monthly'
    groups:
      node-red:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/node-red/projects/adafruithat'
    schedule:
      interval: 'monthly'
    groups:
      node-red:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/node-red/projects/dashboard'
    schedule:
      interval: 'monthly'
    groups:
      node-red:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/node-red/projects/planktoscopehat'
    schedule:
      interval: 'monthly'
    groups:
      node-red:
        patterns:
          - '*'
