setup:
    npm install --omit=dev
    npx vite build
    sudo rm -rf /srv/frontend
    sudo cp -r dist /srv/frontend

setup-dev:
    npm install --include=dev

format:
    npx eslint --fix .

test:
    npx eslint .
    npx vite build
    node --test

dev:
    npx vite --host
