setup:
    npm install --omit=dev
    sudo cp planktoscope-org.backend.service /etc/systemd/system/
    sudo cp polkit.js /etc/polkit-1/rules.d/planktoscope.rules
    sudo systemctl enable planktoscope-org.backend.service

setup-dev:
    npm install --include=dev

format:
    npx eslint --fix .

test:
    npx eslint .
    node --test

dev:
    sudo systemctl stop planktoscope-org.backend.service &> /dev/null
    node --watch src/service.js
