setup:
    uv sync --no-group dev
    sudo cp planktoscope-org.segmenter.service /etc/systemd/system/
    sudo systemctl reenable planktoscope-org.segmenter
    sudo systemctl restart planktoscope-org.segmenter

setup-dev:
    uv sync --group dev

dev:
    -sudo systemctl stop planktoscope-org.segmenter
    uv run main.py

format:
    uv run poe fmt

test:
    uv run poe check
