setup:
    wget https://github.com/filebrowser/filebrowser/releases/download/v2.36.3/linux-arm64-filebrowser.tar.gz -P /tmp
    cd /tmp && tar -xzf /tmp/linux-arm64-filebrowser.tar.gz filebrowser
    -sudo systemctl stop filebrowser
    sudo cp /tmp/filebrowser /usr/local/bin/filebrowser
    sudo cp filebrowser.service /etc/systemd/system/
    sudo systemctl reenable filebrowser
    sudo systemctl restart filebrowser
