#!/bin/env -S bash -eux

sudo apt install yq -y

commit=$(yq -r '.commit' /usr/share/planktoscope/installer-versioning.yml)

cd $HOME/PlanktoScope
git init --initial-branch=master
git remote add origin https://github.com/PlanktoScope/PlanktoScope.git
git fetch origin --filter=blob:none
# "Resets the index but not the working tree (i.e., the changed files are preserved but not marked for commit) and reports what has not been updated."
# https://git-scm.com/docs/git-reset#Documentation/git-reset.txt---mixed
git reset --mixed $commit
