setup:
    sudo apt install -y network-manager firewalld dnsmasq-base
    sudo cp public.xml /etc/firewalld/zones/
    sudo systemctl enable NetworkManager firewalld
    sudo cp -r cfg80211_regdomain.conf /etc/modprobe.d/

setup-dev:
    sudo apt install -y libxml2-utils

format:
    just --fmt --unstable

test:
    just --fmt --check --unstable
    xmllint --noout public.xml
