setup:
    eepmake eeprom_settings.txt planktoscope-hat.eep

    # write
    # sudo gpioset -m signal gpiochip0 26=0 # disable write protect
    sudo eepflash.sh --yes --write --type=24c32 --address=50 --file=planktoscope-hat.eep

    # read
    sudo eepflash.sh --yes --read --type=24c32 --address=50 --file=dump.eep
    eepdump dump.eep dump.txt
    cat dump.txt
