setup:
    sudo apt install -y libgpiod-dev
    npm install --omit=dev
    sudo cp planktoscope-org.eeprom.service /etc/systemd/system/
    sudo systemctl enable planktoscope-org.eeprom.service

setup-dev:
    npm install --include=dev

format:
    npx eslint --fix .

test:
    npx eslint .
    node --test

dev:
    sudo systemctl stop planktoscope-org.eeprom.service &> /dev/null
    node --watch-path . src/service.js
