[WebService]
AllowUnencrypted = true
# Cannot use "*://" or "*"
# add new values after http://raspberrypi.local
# see lib/cockpit.js
Origins = http://192.0.2.1 http://raspberrypi http://raspberrypi.local http://localhost http://192.168.4.1
ProtocolHeader = X-Forwarded-Proto
ForwardedForHeader = X-Forwarded-For
UrlRoot = /admin/cockpit/
