setup:
    # Install cockpit
    # Note: we need to adjust update-initramfs's behavior to make apt-get finish successfully; see
    # https://github.com/PlanktoScope/PlanktoScope/pull/596 and
    # https://github.com/RPi-Distro/repo/issues/382 for details.
    sudo sed -i 's~MODULES=dep~MODULES=most~' /etc/initramfs-tools/initramfs.conf
    sudo apt install -y --no-install-recommends cockpit cockpit-networkmanager cockpit-storaged # cockpit-pcp
    sudo sed -i 's~MODULES=most~MODULES=dep~' /etc/initramfs-tools/initramfs.conf
    sudo cp cockpit.ini /etc/cockpit/cockpit.conf
    # https://cockpit-project.org/guide/latest/feature-pcp
    # sudo systemctl enable pmlogger
    sudo systemctl enable cockpit.socket
    # TODO consider
    # https://github.com/cockpit-project/cockpit-files
    # https://github.com/gbraad-cockpit/cockpit-tailscale
    # https://github.com/gbraad-cockpit/cockpit-headscale

test:
    validator cockpit.ini
