setup:
    just --justfile localization/justfile setup
    just --justfile caddy/justfile        setup
    just --justfile ssh/justfile          setup
    just --justfile cockpit/justfile      setup
    just --justfile filebrowser/justfile  setup
    just --justfile network/justfile      setup
    just --justfile mosquitto/justfile    setup
    just --justfile raspberry/justfile    setup
    just --justfile machine-name/justfile setup
    just --justfile mediamtx/justfile     setup
    just --justfile gpsd/justfile         setup

setup-dev:
    sudo apt install -y shellcheck

test:
    shellcheck **/*.sh
    systemd-analyze verify **/*.service
    just --justfile mediamtx/justfile     test
