setup:
    just --justfile caddy/justfile        setup
    just --justfile machine-name/justfile setup
    just --justfile ssh/justfile          setup
    just --justfile cockpit/justfile      setup
    just --justfile filebrowser/justfile  setup
    just --justfile network/justfile      setup
    just --justfile mosquitto/justfile    setup

setup-dev:
    sudo apt install -y shellcheck
    just --justfile cockpit/justfile      setup-dev
    just --justfile network/justfile      setup-dev

format:
    just --fmt --unstable
    just --justfile caddy/justfile        format
    just --justfile machine-name/justfile format
    just --justfile ssh/justfile          format
    just --justfile cockpit/justfile      format
    just --justfile filebrowser/justfile  format
    just --justfile network/justfile      format

test:
    just --fmt --check --unstable
    shellcheck **/*.sh
    systemd-analyze verify **/*.service
    just --justfile caddy/justfile        test
    just --justfile machine-name/justfile test
    just --justfile ssh/justfile          test
    just --justfile cockpit/justfile      test
    just --justfile filebrowser/justfile  test
    just --justfile network/justfile      test
