setup:
    wget https://github.com/bluenviron/mediamtx/releases/download/v1.15.1/mediamtx_v1.15.1_linux_arm64.tar.gz -P /tmp
    cd /tmp && tar -xf /tmp/mediamtx_v1.15.1_linux_arm64.tar.gz
    -sudo systemctl stop mediamtx
    sudo cp /tmp/mediamtx /usr/local/bin/mediamtx
    sudo cp mediamtx.service /etc/systemd/system/
    sudo systemctl reenable mediamtx
    sudo systemctl restart mediamtx

test:
    validator mediamtx.yml

dev:
    -sudo systemctl stop mediamtx
    mediamtx mediamtx.yml
