setup:
    sudo cp planktoscope-org.controller.imager.service /etc/systemd/system/
    sudo systemctl reenable planktoscope-org.controller.imager
    sudo systemctl restart planktoscope-org.controller.imager

dev:
    -sudo systemctl stop planktoscope-org.controller.imager
    cd .. && uv run python -m imager.main
