# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev656+g56869d2.d19800101'
__version_tuple__ = version_tuple = (0, 1, 'dev656', 'g56869d2.d19800101')
