# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev643+g3c581f6.d19800101'
__version_tuple__ = version_tuple = (0, 1, 'dev643', 'g3c581f6.d19800101')
