setup:
    npm install --omit=dev
    npx parcel build --public-url=/admin/fairscope
    sudo rm -rf /srv/admin
    sudo cp -r dist /srv/admin

setup-dev:
    npm install --include=dev

format:
    npx eslint --fix .

test:
    npx eslint .
    node --test

dev:
    sudo firewall-cmd --zone=public --add-port=1234/tcp &> /dev/null
    npx parcel
    sudo firewall-cmd --zone=public --remove-port=1234/tcp &> /dev/null
