setup:
    npm install --omit=dev
    cd nodes && npm install --without=dev

setup-dev:
    sudo apt install -y jq --no-install-recommends
    npm install --include=dev
    cd nodes && npm install --include=dev

format:
    just --fmt --unstable

test:
    just --fmt --check --unstable
    jq . projects/adafruithat/flows.json 1> /dev/null
    jq . projects/planktoscopehat/flows.json 1> /dev/null
    jq . projects/dashboard/flows.json 1> /dev/null
    cd nodes && npm test

# Too many errors for now
# cd node-red && npx nrlint projects/adafruithat/flows.json
# cd node-red && npx nrlint projects/planktoscopehat/flows.json
# cd node-red && npx nrlint projects/dashboard/flows.json
