setup:
    npm list -g node-red@4.1.3 || npm install -g node-red@v4.1.3
    npm ci --omit=dev
    sudo cp nodered.service /etc/systemd/system/
    sudo mkdir -p /etc/systemd/system/nodered.service.d
    sudo cp 30-override.conf /etc/systemd/system/nodered.service.d/
    sudo systemctl reenable nodered
    sudo systemctl restart nodered
    rm -rf /home/pi/.node-red

setup-dev:
    npm install --include=dev

dev:
    -sudo systemctl stop nodered
    node --watch-path ~/PlanktoScope/node-red/nodes/ ~/.local/bin/node-red --settings ~/PlanktoScope/node-red/settings.cjs

test:
    validator projects/dashboard/flows.json
    npx eslint .
    cd nodes && node --test

# Too many errors for now
# cd node-red && npx nrlint projects/dashboard/flows.json
