setup:
    npm install --omit=dev
    cd nodes && npm install --without=dev
    sudo systemctl enable nodered

setup-dev:
    GOBIN=~/.local/bin go install github.com/Boeing/config-file-validator/cmd/validator@v1.8.0
    npm install --include=dev
    cd nodes && npm install --include=dev

format:
    just --fmt --unstable

test:
    just --fmt --check --unstable
    validator projects/adafruithat/flows.json
    validator projects/planktoscopehat/flows.json
    validator projects/dashboard/flows.jso
    cd nodes && npm test

# Too many errors for now
# cd node-red && npx nrlint projects/adafruithat/flows.json
# cd node-red && npx nrlint projects/planktoscopehat/flows.json
# cd node-red && npx nrlint projects/dashboard/flows.json
