setup:
    sudo apt install -y caddy
    sudo cp Caddyfile /etc/caddy/
    sudo systemctl enable caddy
    sudo systemctl restart caddy

format:
    caddy fmt --overwrite Caddyfile

test:
    caddy validate Caddyfile
