setup:
    # required for python-picamera2
    # we are not using python3-camera2 from apt because of the amount of dependencies
    sudo apt install -y --no-install-recommends gcc libcap-dev libpython3-dev python3-libcamera python3-kms++ i2c-tools
    uv venv --clear --system-site-packages
    uv sync --no-group dev
    sudo cp planktoscope-org.controller.service /etc/systemd/system/
    sudo systemctl reenable planktoscope-org.controller
    sudo systemctl restart planktoscope-org.controller

setup-dev:
    uv sync --group dev

dev:
    -sudo systemctl stop planktoscope-org.controller
    uv run main.py

format:
    uv run poe fmt

test:
    uv run poe check
