setup:
    # required for python-picamera2
    # we are not using python-camera2 from apt because of the amount of dependencies
    sudo apt install -y --no-install-recommends gcc libcap-dev libpython3-dev python3-libcamera python3-kms++ i2c-tools
    poetry lock && poetry install --without=dev
    sudo apt purge -y gcc libcap-dev libpython3-dev
    sudo cp planktoscope-org.controller.service /etc/systemd/system/
    sudo systemctl reenable planktoscope-org.controller
    sudo systemctl restart planktoscope-org.controller

setup-dev:
    poetry lock && poetry install --with=dev

dev:
    -sudo systemctl stop planktoscope-org.controller
    poetry run python -u main.py

format:
    poetry run poe fmt

test:
    poetry run poe check
