setup:
    sudo apt install -y imgp
    uv sync
    uv run poe build
    sudo rm -rf /srv/docs
    sudo cp -r site /srv/docs

setup-dev:
    uv sync

dev:
    uv run poe preview

test:
    uv run poe check
