name: Build node-red

on:
  push:
    branches:
      - 'main'
      - 'software/beta'
      - 'software/stable'
    tags:
      - 'v*'
    paths:
      - 'node-red/nodes/**'
      - '.github/workflows/build-node-red.yml'
  pull_request:
    paths:
      - 'node-red/nodes/**'
      - '.github/workflows/build-node-red.yml'
  merge_group:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref (optional)'
        required: false

jobs:
  ci-checks:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
        cache-dependency-path: node-red/nodes/package-lock.json

      - name: npm ci
