---
name: build-os-bookworm-dx
on:
  push:
    branches:
      - 'master'
      - 'software/beta'
      - 'software/stable'
    tags:
      - 'software/v*'
    paths:
      - 'software/**'
      - '.github/workflows/build-os*.yml'
  pull_request:
    paths:
      - 'software/**'
      - '.github/workflows/build-os*.yml'
  #merge_group:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref (optional)'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        variant:
          - none
          - segmenter-only
        arch:
          - arm64
        base_variant_name:
          # We haven't set up networking on bookworm, so the lite image is useless and hard to make
          # usable; so we just build the desktop image:
          - desktop
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-os.yml
    secrets: inherit
    with:
      name: rpi-forklift-demo
      base_release_name: bookworm
      base_image_variant: ${{ matrix.base_variant_name }}
      base_release_date: 2024-03-15
      arch: ${{ matrix.arch }}
      variant: ${{ matrix.variant }}
