---
name: build-os-bullseye-fairscope
on:
  push:
    branches:
      - 'master'
      - 'software/beta'
      - 'software/stable'
    tags:
      - 'software/v*'
    paths:
      - 'software/**'
      - '!software/CHANGELOG.md'
      - '.github/workflows/build-os*.yml'
  pull_request:
    paths:
      - 'software/**'
      - '.github/workflows/build-os*.yml'
  merge_group:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref (optional)'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        variant:
          - fairscope-latest
        base_variant_name:
          - lite
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-os.yml
    secrets: inherit
    with:
      name: planktoscope
      base_release_name: bullseye
      base_image_variant: ${{ matrix.base_variant_name }}
      base_release_date: 2024-10-28
      base_file_release_date: 2024-10-22
      arch: arm64
      variant: ${{ matrix.variant }}
