name: Build the hardware controller

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'software/beta'
      - 'software/stable'
    tags:
      - 'v*'
    paths:
      - 'device-backend/control/**'
      - '.github/workflows/control-*.yml'
  pull_request:
    paths:
      - 'device-backend/control/**'
      - '.github/workflows/control-*.yml'
  merge_group:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref (optional)'
        required: false

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: device-backend-control

jobs:
  ci-checks:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==2.1.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'
          cache-dependency-path: |
            device-backend/control/poetry.lock

      - name: Install build dependencies
        working-directory: ./device-backend/control
        run: |
          sudo apt-get install -y libcap-dev
          poetry install --with dev --no-root

      - name: Run checks
        working-directory: ./device-backend/control
        run: poetry run poe check
