name: Deploy documentation

on:
  push:
    branches:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


defaults:
  run:
    shell: bash

jobs:
  deploy-edge:
    environment:
      name: documentation-edge
      url: https://docs-edge.planktoscope.community
    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest
    # queued. But do not cancel in-progress runs - we want these deployments to complete.
    concurrency:
      group: edge-pages
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Install poetry
        run: pipx install poetry==1.5.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
          cache-dependency-path: |
            documentation/poetry.lock

      - name: Install build dependencies
        run: |
          poetry -C ./documentation/ install --with docs

      - name: Import external assets
        run: poetry -C ./documentation/ run poe --root ./documentation/ import-external-assets

      - name: Build documentation
        run: poetry -C ./documentation/ run poe --root ./documentation/ build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./documentation/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  deploy-beta:
    environment:
      name: documentation-beta
      url: https://docs-beta.planktoscope.community
    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest
    # queued. But do not cancel in-progress runs - we want these deployments to complete.
    concurrency:
      group: beta-pages
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.5.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
          cache-dependency-path: |
            documentation/poetry.lock

      - name: Install build dependencies
        run: |
          poetry -C ./documentation/ install --with docs

      - name: Import external assets
        run: poetry -C ./documentation/ run poe --root ./documentation/ import-external-assets

      - name: Build documentation
        run: poetry -C ./documentation/ run poe --root ./documentation/ build

      - name: Push to ${{ vars.REPOSITORY_NAME }}
        uses: cpina/github-action-push-to-another-repository@v1
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DOCS_BETA_SSH_DEPLOY_KEY }}
        with:
          source-directory: documentation/site/
          destination-github-username: PlanktoScope
          destination-repository-name: ${{ vars.REPOSITORY_NAME }}
          user-email: github-actions[bot]@users.noreply.github.com
          user-name: github-actions[bot]
          commit-message: Deploy ORIGIN_COMMIT
          target-branch: main
