name: deploy-documentation/beta

on:
  push:
    branches:
      - 'documentation/beta'
  workflow_call:
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest
# queued. But do not cancel in-progress runs - we want these deploymeents to complete.
concurrency:
  group: 'docs-beta-deploy'
  cancel-in-progress: false

env:
  DESTINATION_OWNER: ${{ github.repository_owner }}

defaults:
  run:
    shell: bash

jobs:
  deploy:
    environment:
      name: documentation-beta
      url: ${{ vars.URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: documentation/beta

      - name: Install dependencies for mkdocs-material image-processing libraries
        run: sudo apt-get -y install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev imgp pngquant

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        working-directory: ./documentation
        run: |
          uv sync --locked

      - name: Set release channel
        working-directory: documentation
        run: uv run poe set-beta-release-channel

      - name: Build documentation
        env:
          DOCS_DEPLOY: true
          DOCS_SITEURL: ${{ vars.URL }}
        working-directory: documentation
        run: uv run poe build

      - name: Push to ${{ vars.REPOSITORY_NAME }}
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: documentation/site/
          destination-github-username: ${{ env.DESTINATION_OWNER }}
          destination-repository-name: ${{ vars.REPOSITORY_NAME }}
          user-email: github-actions[bot]@users.noreply.github.com
          user-name: github-actions[bot]
          commit-message: Deploy ORIGIN_COMMIT
          target-directory: site
