---
name: release-channel-documentation/beta
on:
  push:
    tags:
      - 'documentation/v[0-9]+.[0-9]+.[0-9]+-beta.*'
      # We want to advance the documentation/beta branch to the latest stable release, too:
      - 'documentation/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  ff-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git checkout documentation/beta
          git merge --ff-only ${{ github.ref_name }}

      - uses: ad-m/github-push-action@v0.8.0
        with:
          branch: documentation/beta

  deploy-docs-site:
    # We call this workflow manually because it doesn't appear to be triggered automatically by a
    # push of the documentation/beta branch from the ff-branch job:
    uses: ./.github/workflows/documentation-deploy-beta.yml
    needs: ff-branch
    secrets: inherit
