---
name: release-channel-documentation-beta
on:
  push:
    tags:
      - 'documentation/v[0-9]+.[0-9]+.[0-9]+-beta.*'

jobs:
  ff-branch-documentation-beta:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git checkout documentation/beta
          git merge --ff-only ${{ github.ref_name }}

      - uses: ad-m/github-push-action@v0.8.0
        with:
          branch: documentation/beta
