---
name: release-channel-software/beta
on:
  push:
    tags:
      - 'software/v[0-9]+.[0-9]+.[0-9]+-beta.*'
      # We want to advance the beta branch to the latest stable release, too:
      - 'software/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  ff-branch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git checkout software/beta
          git merge --ff-only ${{ github.ref_name }}

      - uses: ad-m/github-push-action@v0.8.0
        with:
          branch: software/beta
